//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Users = new HashSet<User>();
        }
    
        public int id { get; set; }
        public string House { get; set; }
        public string Road { get; set; }
        public string City { get; set; }
        public string Postal_Code { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
