//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Category
    {
        public Service_Category()
        {
            this.Services = new HashSet<Service>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string details { get; set; }
    
        public virtual ICollection<Service> Services { get; set; }
    }
}
