//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Applications = new HashSet<Application>();
        }
    
        public int id { get; set; }
        public int userid { get; set; }
        public Nullable<double> salary { get; set; }
        public Nullable<int> service_id { get; set; }
        public string work_area { get; set; }
        public string work_status { get; set; }
    
        public virtual ICollection<Application> Applications { get; set; }
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
    }
}
