//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int id { get; set; }
        public int userid { get; set; }
        public string access_token { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> expired_at { get; set; }
    }
}
